### ISSUE TITLE
assign zenodo DOI to project

### ISSUE THREAD

**Issue by szorowi1** [nimh-dsst/OpenCogData#8]

**Comment by ericearl** [comment]
@szorowi1 lmk if you want/need any help with this. Happy to help!

**Comment by szorowi1** [comment]
@ericearl thanks so much for volunteering to help with this! I was planning on taking care of this later today/tomorrow. but if I'm holding anything up, please feel free to take care of it sooner!

**Comment by szorowi1** [comment]
Integrated with Zenodo at https://zenodo.org/records/10257543
